version: '3.6'

services:
  app-server:
    image: blaurent/go-demo-app
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 2
    networks:
      - sidecar-network
    environment:
      - PORT=8080

  https-proxy:
    image: dockercloud/haproxy
    depends_on:
      - app-server
    environment:
      - BALANCE=leastconn
      - CERT_FOLDER=/certs/
      - CERT_FILE=/certs/haproxy-selfsigned.pem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/certs:/certs
    networks:
      - sidecar-network
    ports:
      - 8084:443
      - 8085:80
      - 8086:1936

networks:
  sidecar-network:
    driver: overlay
