---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set nginx_use_service = True, if not defined
  set_fact:
    nginx_use_service: True
  when: nginx_use_service is not defined

- name: set nginx_in_selinux = True, judging from the context
  set_fact:
    nginx_in_selinux: True
  when: nginx_in_selinux is not defined and ansible_selinux == true or (ansible_selinux.status is defined and ansible_selinux.status == "enabled")
