sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04  -t nginx_trusty   .
    - docker build  -f test/Dockerfile-ubuntu12.04  -t nginx_precise  .
    - docker build  -f test/Dockerfile-debian8      -t nginx_jessie   .
    - docker build  -f test/Dockerfile-debian7      -t nginx_wheezy   .
    - docker build  -f test/Dockerfile-centos7      -t nginx_centos7  .
    - docker build  -f test/Dockerfile-centos6      -t nginx_centos6  .
    - docker build  -f test/Dockerfile-alpine3      -t nginx_alpine3  .

script:
    - docker run  -v $(pwd):/data  nginx_trusty
    - docker run  -v $(pwd):/data  nginx_precise
    - docker run  -v $(pwd):/data  nginx_jessie
    - docker run  -v $(pwd):/data  nginx_wheezy

    - docker run  -d --name c5  -v $(pwd):/data -v /sys/fs/cgroup:/sys/fs/cgroup:ro  nginx_centos7  /usr/sbin/init
    - sleep 10
    - docker exec -it c5 run-test.sh

    - docker run  -v $(pwd):/data  nginx_centos6
    - docker run  -v $(pwd):/data  nginx_alpine3


    - echo "==> Validating the test results..."
    - grep '^Active connections' result-ubuntu14.04
    - grep '^Active connections' result-ubuntu12.04
    - grep '^Active connections' result-debian8
    - grep '^Active connections' result-debian7
    - grep '^Active connections' result-centos7
    - grep '^Active connections' result-centos6
    - grep '^Active connections' result-alpine3


notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
