version: '3.6'

services:
  app-server:
    image: blaurent/go-demo-app
    restart: unless-stopped
    expose:
      - 8080
    environment:
      - PORT=8080

  https-proxy:
    image: dockercloud/haproxy
    depends_on:
      - app-server
    environment:
      - BALANCE=leastconn
      - CERT_FOLDER=/certs/
      - CERT_FILE=/certs/haproxy-selfsigned.pem
    links:
      - app-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/certs:/certs
    ports:
      - 8084:443
      - 8085:80
      - 8086:1936
